version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    ports:
      - 6379:6379
  yakutia_backend:
    container_name: yakutia_backend
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - redis
